data <- read.table("household_power_consumption.txt", header = T, sep=";", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"), na.strings="?")
data <- transform(data, DateTime = as.POSIXct(paste(Date,Time), f= "%d/%m/%Y %H:%M:%S"))
data <- subset(subset(data, DateTime >= as.POSIXct("2007-02-01 00:00:00", f="%Y-%m-%d %H:%M:%S")), DateTime <= as.POSIXct("2007-02-02 23:59:00", f="%Y-%m-%d %H:%M:%S"))
par(mfrow=c(2,2))
plot(data$DateTime, data$Global_active_power, xlab = "", ylab="Global Active Power", type="l")
plot(data$DateTime, data$Voltage, xlab = "datetime", ylab="Voltage", type="l")
plot(data$DateTime, data$Sub_metering_1, col="black", xlab="", ylab="Energy sub heading", type="l")
lines(data$DateTime, data$Sub_metering_2, col="red", type="l")
lines(data$DateTime, data$Sub_metering_3, col="blue", type="l")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1, bty="n")
plot(data$DateTime, data$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l")
dev.copy(png, "plot4.png")
dev.off()